### ISSUE TITLE
esri-dump is now throwing an error with current dependencies

### ISSUE THREAD

**Issue by tlpinney** [openaddresses/esri-dump#13]
<pre>
mbp:esri-dump user$ node index.js http://gis.apgov.us/APGarcGIS/rest/services/Maps/ParcelBasemap/MapServer/2

module.js:340
    throw err;
          ^
Error: Cannot find module 'd/d'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/user/testdump/esri-dump/node_modules/es6-set/polyfill.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
</pre>

**Comment by ingalls** [comment]
I'm no longer seeing this error on a fresh install. Feel free to reopen if this problem continues.
