### ISSUE TITLE
'geometry' parameter is invalid,Unable to complete Query operation.

### ISSUE THREAD

**Issue by robsalasco** [openaddresses/esri-dump#30]
Hi! Can you help me please?
Thank you for your work!

```
robsalasco@leucippus:~/Desktop/FONDECYT_ENVIRONMENT/WMS_CONAF$ esri-dump http://mapaforestal.infor.cl/ArcGIS/rest/services/20160803_pl_apl/MapServer/6 > 20160803_pl_apl_6.geojson
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: {"code":400,"message":"Unable to complete  operation.","details":["'geometry' parameter is invalid","Unable to complete Query operation."]}
    at Request._callback (/Users/robsalasco/.nodenv/versions/6.6.0/lib/node_modules/esri-dump/lib/geometry.js:48:39)
    at Request.self.callback (/Users/robsalasco/.nodenv/versions/6.6.0/lib/node_modules/esri-dump/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/robsalasco/.nodenv/versions/6.6.0/lib/node_modules/esri-dump/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/robsalasco/.nodenv/versions/6.6.0/lib/node_modules/esri-dump/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
```

**Comment by iandees** [comment]
Since it's a server error, you're going to run into it no matter which language you use 😄 . See https://github.com/openaddresses/pyesridump/issues/32.
