### ISSUE TITLE
Invalid URL (Z Data Error)

### ISSUE THREAD

**Issue by stenuto** [openaddresses/esri-dump#40]
I can't get this library to work using this url: `https://gismaps.kingcounty.gov/arcgis/rest/services/Transit/TransitGrievanceTracking/MapServer/1`

I'm getting this error:

`TypeError [ERR_INVALID_URL]: Invalid URL
    at new NodeError (node:internal/errors:399:5)
    at new URL (node:internal/url:556:13)
    at new EsriDump (file:///Users/stephentenuto/Dev/parcel-downloader/node_modules/esri-dump/dist/index.js:40:20)
    at file:///Users/stephentenuto/Dev/parcel-downloader/index.js:13:14
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25) {
  input: 'esri-dump',
  code: 'ERR_INVALID_URL'
}
`

I've used `fetch` with this URL before and got a Z Data Error. I ended up having to use the 'got' NPM library instead of fetch.

**Comment by ingalls** [comment]
The server you are referencing seems to be returning a Content-Encoding header without actually encoding the content by my very preliminary investigation. For now I've set the default value of the `Accept-Encoding` header to be `gzip`.

This is fixed in version 4.2.0
